<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ImarketingB2B</title>
<link rel="stylesheet" href="/public/iM/css/style.css" type="text/css">
<script src="/public/iM/js//html5.js" type="text/javascript"></script>
<script src="/public/iM/js//jquery.js" type="text/javascript"></script>
<!-- watermark starts -->
<script type="text/javascript" src="/public/iM/js//watermark.js"></script>
<script type="text/javascript">
            var Init = function() {
                watermark("email", "Your Email Address");           
                watermark("password", "Your Password");           
                         }
            if (window.addEventListener)
                window.addEventListener("load", Init, false)
            else if (window.attachEvent)
                window.attachEvent("onload", Init)
            else if (document.getElementById)
                window.onload = Init;
    
</script>
<!-- watermark ends -->
<!-- colorbox starts -->
<link type="text/css" media="screen" rel="stylesheet" href="/public/iM/css/colorbox.css" />
<script type="text/javascript" src="/public/iM/js//jquery.colorbox.js"></script>
<script type="text/javascript" id="js">
$(document).ready(function() {
	// call the tablesorter plugin
		$(".example6").colorbox({iframe:false, innerWidth:255, innerHeight:203});
				
	
});
</script>
<!-- colorbox ends -->
</head>
<body>
<div class="layout">
  <!-- header starts -->
  <div class="header-outer">
    <header>
      <div class="logo"><a href="/index/index"><img src="/public/iM/images/logo.jpg" alt="logo" /></a></div>
      <div class="top-right">
        <div class="register">
          <ul>
            <li><a href="#">Signup</a></li>
            <li class="brdr-right"><a href="#">Sign In </a>
              <div class="cl"></div>
              <div class="signinBox"> <span class="topbg"></span>
                <div class="midbg">
                  <div class="container">
                    <h2>Sign In to iMarketing B2B</h2>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="email" />
                    </div>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="password" />
                    </div>
                    <div class="row2">
                      <input name="" type="image" src="/public/iM/images/submit-btn-bg.png" value="submit" />
                      <span><a href="#">Forgot password?</a></span></div>
                  </div>
                </div>
                <span class="bottbg"></span> </div>
            </li>
          </ul>
        </div>
        <div class="cl"></div>
        <nav class="nav">
          <ul>
            <li class="first"><a href="index">Home </a></li>
            <li><a href="/index/products"> Products </a></li>
            <li><a href="/index/api"> API </a></li>
            <li><a class="cur" href="/index/algopricing"> Pricing </a></li>
            <li><a href="/index/about"> About Us </a></li>
            <li><a href="/index/jobs"> Jobs</a></li>
          </ul>
        </nav>
      </div>
      <div class="cl"></div>
    </header>
  </div>
  <!-- header ends -->
  <!-- inner page links -->
  <div class="submenu-outer">
    <div class="submenu">
      <h2> Algo - Intelligent FAQ</h2>
    </div>
  </div>
  <!-- inner page links ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="inner-body">
      <div class="content-div">
        <p>With the help of algorithms.io machine learning &amp; text/ phrase mapping technique, iMarketingB2B is able to offer an intelligent system that automatically creates/manages FAQs. As new FAQs come into system, we will automatically combine &amp; categories the questions and link them to  answers with the higest ratings. If the answer (output) is not accepted, user can request for a second look which will decrease the rating of the answer.</p>
      </div>
      <div class="algo-pricing-container">
        <div class="heading-bg">
          <div class="colum"> <span>BASIC</span> </div>
          <div class="colum"> Premium </div>
          <div class="colum"> Plus </div>
          <div class="colum"> Enterprise </div>
          <div class="cl"></div>
        </div>
        <div class="repeat-bg">
          <div class="sep-row padding1">
            <div class="colum">
              <h3 class="free">Free </h3>
            </div>
            <div class="colum">
              <h3> $1,500 set up Fee <br>
                +<br>
                $199/Month </h3>
            </div>
            <div class="colum">
              <h3> $6,500 set up Fee <br>
                +<br>
                $799/Month </h3>
            </div>
            <div class="colum">
              <h3 class="free">Call Us </h3>
            </div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> 20 FAQ Inputs </div>
            <div class="colum"> 200 FAQ Inputs </div>
            <div class="colum"> 2,000 FAQ Inputs </div>
            <div class="colum"> Unlimited Inputs </div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> 50 Outputs / Mnth</div>
            <div class="colum"> 500 Outputs / Mnth</div>
            <div class="colum">5,000 Outputs / Mnth</div>
            <div class="colum"> Unlimited Outputs</div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> Continuous Learning </div>
            <div class="colum"> Continuous Learning</div>
            <div class="colum">Continuous Learning</div>
            <div class="colum"> Continuous Learning</div>
            <div class="cl"></div>
          </div>
          <div class="sep-row">
            <div class="colum"> Unlimited Support</div>
            <div class="colum"> Unlimited Support</div>
            <div class="colum"> Unlimited Support</div>
            <div class="colum"> Unlimited Support</div>
            <div class="cl"></div>
          </div>
          <div class="sep-row last">
            <div class="colum"> <a class="example6" href="/index/login" title=""><img src="/public/iM/images/signup-now-btn.png" width="176" height="44" alt="signup-btn" /></a> </div>
            <div class="colum"><a class="example6" href="/index/login" title=""><img src="/public/iM/images/signup-now-btn.png" width="176" height="44" alt="signup-btn" /></a> </div>
            <div class="colum"> <a class="example6" href="/index/login" title=""><img src="/public/iM/images/signup-now-btn.png" width="176" height="44" alt="signup-btn" /></a> </div>
            <div class="colum"><a class="example6" href="/index/login" title=""><img src="/public/iM/images/signup-now-btn.png" width="176" height="44" alt="signup-btn" /></a> </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="bottom-curve">&nbsp;</div>
      </div>
    </div>
  </div>
  <!-- body ends -->
  <!-- footer starts -->
  <div class="footer-outer">
    <footer>
      <div class="btm-logo"><img src="/public/iM/images/bottom-logo.jpg" alt="bottom-logo" /></div>
      <div class="footer-links-container">
        <ul class="btm-links">
          <li class="first"><a href="index">Home </a></li>
          <li><a href="/index/products"> Products </a></li>
          <li><a href="/index/api"> API </a></li>
          <li><a href="/index/algo-pricing"> Pricing </a></li>
          <li><a href="/index/about"> About Us </a></li>
          <li><a href="/index/jobs"> Jobs</a></li>
        </ul>
        <p class="copyrights">&copy; Copyright 2012 iMarketing B2B.com . All Rights Reserved</p>
        <div class="cl"></div>
      </div>
      <div class="cl"></div>
    </footer>
  </div>
  <!-- footer ends -->
</div>
</body>
</html>
