<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ImarketingB2B</title>
<link rel="stylesheet" href="/public/iM/css/style.css" type="text/css">
<script src="/public/iM/js//html5.js" type="text/javascript"></script>
<script src="/public/iM/js//jquery.js" type="text/javascript"></script>
<!-- watermark starts -->
<script type="text/javascript" src="/public/iM/js//watermark.js"></script>
<script type="text/javascript">
            var Init = function() {
                watermark("email", "Your Email Address");           
                watermark("password", "Your Password");           
                         }
            if (window.addEventListener)
                window.addEventListener("load", Init, false)
            else if (window.attachEvent)
                window.attachEvent("onload", Init)
            else if (document.getElementById)
                window.onload = Init;
    
</script>
<!-- watermark ends -->
</head>
<body>
<div class="layout">
  <!-- header starts -->
  <div class="header-outer">
    <header>
      <div class="logo"><a href="/index/index"><img src="/public/iM/images/logo.jpg" alt="logo" /></a></div>
      <div class="top-right">
        <div class="register">
          <ul>
            <li><a href="#">Signup</a></li>
            <li class="brdr-right"><a href="#">Sign In </a>
              <div class="cl"></div>
              <div class="signinBox"> <span class="topbg"></span>
                <div class="midbg">
                  <div class="container">
                    <h2>Sign In to iMarketing B2B</h2>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="email" />
                    </div>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="password" />
                    </div>
                    <div class="row2">
                      <input name="" type="image" src="/public/iM/images/submit-btn-bg.png" value="submit" />
                      <span><a href="#">Forgot password?</a></span></div>
                  </div>
                </div>
                <span class="bottbg"></span> </div>
            </li>
          </ul>
        </div>
        <div class="cl"></div>
        <nav class="nav">
          <ul>
            <li class="first"><a href="index">Home </a></li>
            <li><a href="/index/products"> Products </a></li>
            <li><a href="/index/api" class="cur"> API </a></li>
            <li><a href="/index/algopricing"> Pricing </a></li>
            <li><a href="/index/about"> About Us </a></li>
            <li><a href="/index/jobs"> Jobs</a></li>
          </ul>
        </nav>
      </div>
      <div class="cl"></div>
    </header>
  </div>
  <!-- header ends -->
  <!-- inner page links -->
  <div class="submenu-outer">
    <div class="submenu">
      <h2> Api </h2>
    </div>
  </div>
  <!-- inner page links ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="inner-body">
      <div class="content-div">
        <h4> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In suscipit, magna quis commodo volutpat, felis neque iaculis libero, sed sollicitudin leo tortor ut diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec interdum auctor pellentesque. Integer tempus sapien mi. Proin lacus sem, tincidunt ultrices vestibulum ut, vehicula ut massa. </h4>
        <p>Nunc imperdiet nulla sit amet lorem ornare faucibus. Nullam varius tempus dui, ut euismod leo blandit at. Cras velit sapien, euismod bibendum ullamcorper sit amet, posuere et dui. Suspendisse tempor semper libero, at suscipit neque rhoncus et. Fusce sed nibh massa. Aliquam erat volutpat. Integer faucibus vulputate odio ac lacinia. Nulla tempus dictum nisl, quis condimentum lorem mollis in. Aenean fermentum posuere odio et molestie. Vivamus nec nisi lorem. Curabitur sollicitudin, nibh et tincidunt placerat, metus mauris vulputate tellus, non viverra eros velit convallis metus.</p>
        <p>Maecenas pulvinar, tortor eu lobortis scelerisque, leo orci posuere dui, et congue est nunc at est. Sed lorem justo, molestie ac varius vel, vulputate in augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi pulvinar molestie tellus, a porttitor tellus varius eu. Aliquam erat volutpat. In elementum pretium lectus scelerisque pharetra. Proin tincidunt vestibulum nisl, a malesuada neque mollis a. Ut aliquet tortor sit amet enim hendrerit porttitor in a neque. Maecenas accumsan dui vitae tellus molestie condimentum.</p>
        <p>Fusce sollicitudin metus at diam posuere pulvinar. Nam at lorem mi. Nullam varius sapien vitae mi pulvinar ut mollis lectus blandit. Nullam gravida mauris consequat mauris mattis nec bibendum metus condimentum. Curabitur ante libero, sollicitudin ut cursus eget, dignissim eget velit. Aenean pulvinar quam in quam porttitor eu laoreet nunc dapibus. Sed eget massa arcu. Vestibulum non lorem ac arcu blandit elementum id id justo. Nam ante felis, auctor vitae molestie non, pretium non nulla. Phasellus porttitor velit a ante blandit sagittis. Donec eget ante purus, eu mollis massa. Curabitur nulla tellus, laoreet sed dignissim id, tempus ac turpis. Donec nec erat felis. Cras in ipsum a neque lobortis vulputate sit amet in magna.</p>
        <p>Nullam placerat vestibulum sapien, ac blandit dolor venenatis non. Aliquam laoreet cursus lorem, in tincidunt turpis volutpat in. Integer a nisi dui, vel feugiat lacus. Proin sit amet malesuada sem. Aenean tincidunt lobortis neque, sed aliquet diam rutrum eget. Donec volutpat nisl quis mi luctus pulvinar a a mi. Nulla auctor orci ac libero vehicula tempor. Pellentesque malesuada nibh magna. Nunc placerat mattis metus, sed molestie mauris interdum at. Curabitur porttitor, enim ac tincidunt dignissim, metus tortor condimentum mauris, at pulvinar odio diam eu eros. Donec eleifend, orci et vulputate consequat, arcu enim tristique mi, eu viverra nunc mauris bibendum elit. Cras malesuada venenatis risus. Nunc laoreet, neque in aliquet porta, risus nulla porta quam, sit amet dignissim neque nisi in nisi. Vestibulum at mi id dui molestie imperdiet. Quisque neque augue, egestas sed pulvinar id, tempus vel orci.</p>
        <p>Mauris lobortis accumsan velit eget mattis. Maecenas iaculis mauris non justo dapibus in fermentum metus dictum. Curabitur mattis justo at risus consequat gravida sodales arcu mollis. Donec turpis neque, vestibulum et sollicitudin vitae, malesuada ac erat. Nullam a luctus est. Suspendisse id lorem sed leo facilisis euismod. Nam ullamcorper nisi at sapien lacinia condimentum. Etiam vel velit vel nunc rhoncus vestibulum. Aenean rutrum venenatis eros eget tincidunt. </p>
        <p>Nunc imperdiet nulla sit amet lorem ornare faucibus. Nullam varius tempus dui, ut euismod leo blandit at. Cras velit sapien, euismod bibendum ullamcorper sit amet, posuere et dui. Suspendisse tempor semper libero, at suscipit neque rhoncus et. Fusce sed nibh massa. Aliquam erat volutpat. Integer faucibus vulputate odio ac lacinia. Nulla tempus dictum nisl, quis condimentum lorem mollis in. Aenean fermentum posuere odio et molestie. Vivamus nec nisi lorem. Curabitur sollicitudin, nibh et tincidunt placerat, metus mauris vulputate tellus, non viverra eros velit convallis metus.</p>
        <p>Maecenas pulvinar, tortor eu lobortis scelerisque, leo orci posuere dui, et congue est nunc at est. Sed lorem justo, molestie ac varius vel, vulputate in augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi pulvinar molestie tellus, a porttitor tellus varius eu. Aliquam erat volutpat. In elementum pretium lectus scelerisque pharetra. Proin tincidunt vestibulum nisl, a malesuada neque mollis a. Ut aliquet tortor sit amet enim hendrerit porttitor in a neque. Maecenas accumsan dui vitae tellus molestie condimentum.</p>
      </div>
    </div>
  </div>
  <!-- body ends -->
  <!-- footer starts -->
  <div class="footer-outer">
    <footer>
      <div class="btm-logo"><img src="/public/iM/images/bottom-logo.jpg" alt="bottom-logo" /></div>
      <div class="footer-links-container">
        <ul class="btm-links">
          <li class="first"><a href="index">Home </a></li>
          <li><a href="/index/products"> Products </a></li>
          <li><a href="/index/api"> API </a></li>
          <li><a href="/index/algopricing"> Pricing </a></li>
          <li><a href="/index/about"> About Us </a></li>
          <li><a href="/index/jobs"> Jobs</a></li>
        </ul>
        <p class="copyrights">&copy; Copyright 2012 iMarketing B2B.com . All Rights Reserved</p>
        <div class="cl"></div>
      </div>
      <div class="cl"></div>
    </footer>
  </div>
  <!-- footer ends -->
</div>
</body>
</html>
