<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ImarketingB2B</title>
<link rel="stylesheet" href="/public/iM/css/style.css" type="text/css">
<script src="/public/iM/js/html5.js" type="text/javascript"></script>
<!-- watermark starts -->
<script type="text/javascript" src="/public/iM/js/jquery.js"></script>
<script type="text/javascript" src="/public/iM/js/jquery-1.2.3.pack.js"></script>
<script type="text/javascript" src="/public/iM/js/jquery.jcarousel.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/public/iM/css/jquery.jcarousel.css" />
<link rel="stylesheet" type="text/css" href="/public/iM/css/skin.css" />
<script type="text/javascript">
jQuery(document).ready(function() {
    jQuery('#mycarousel').jcarousel();
});
</script>
<script type="text/javascript" src="/public/iM/js/watermark.js"></script>
<script type="text/javascript">
            var Init = function() {
                watermark("email", "Your Email Address");           
                watermark("password", "Your Password");           
                         }
            if (window.addEventListener)
                window.addEventListener("load", Init, false)
            else if (window.attachEvent)
                window.attachEvent("onload", Init)
            else if (document.getElementById)
                window.onload = Init;
    
</script>
<!-- watermark ends -->
</head>
<body>
<div class="layout">
  <!-- header starts -->
  <div class="header-outer">
    <header>
      <div class="logo"><a href="index"><img src="/public/iM/images/logo.jpg" alt="logo" /></a></div>
      <div class="top-right">
        <div class="register">
          <ul>
            <li><a href="#">Signup</a></li>
            <li class="brdr-right"><a href="#">Sign In </a>
              <div class="cl"></div>
              <div class="signinBox"> <span class="topbg"></span>
                <div class="midbg">
                  <div class="container">
                    <h2>Sign In to iMarketing B2B</h2>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="email" />
                    </div>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="password" />
                    </div>
                    <div class="row2">
                      <input name="" type="image" src="/public/iM/images/submit-btn-bg.png" value="submit" />
                      <span><a href="#">Forgot password?</a></span></div>
                  </div>
                </div>
                <span class="bottbg"></span> </div>
            </li>
          </ul>
        </div>
        <div class="cl"></div>
        <nav class="nav">
          <ul>
            <li class="first"><a href="index" class="cur">Home </a></li>
            <li><a href="/index/products"> Products </a></li>
            <li><a href="/index/api"> API </a></li>
            <li><a href="/index/algopricing"> Pricing </a></li>
            <li><a href="/index/about"> About Us </a></li>
            <li><a href="/index/jobs"> Jobs</a></li>
          </ul>
        </nav>
      </div>
      <div class="cl"></div>
    </header>
  </div>
  <!-- header ends -->
  <!-- body starts -->
  <div class="homebody-outer">
    <div class="homebody-body">
      <div class="banner">
        <div class="weltxt">
          <span>Machine Learning Algorithms</span>
          <h1>Providing Marketing Intelligence</h1>
          <p>Selling is an action used to convince a buyer they must have an item you are selling.</p>
          <p>Marketing is an action used ensure you already have the item in your hand the a buyer wants.</p>
          <p>iMarketing B2B is an artificial intelligence platform that intelligently recommends what product to keep in your hand</p>
          <a href="#"><img src="/public/iM/images/see-our-reco-btn.png" alt="know more" /></a> </div>
        <div class="picture"><img src="/public/iM/images/home-banner-img.jpg" alt="know more" /></div>
        <div class="cl"></div>
      </div>
<!--
      <div class="featuredOn">
        <div class="txtDiv">
          <h2>Featured On</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum lacinia nunc a tincidunt.</p>
        </div>
        <div class="logoarea">
          <div id="mycarousel" class="relvideobox jcarousel-skin-tango">
            <ul>
              <li><a href='#'><img src="/public/iM/images/techCrunch-logo.png" alt="" /></a></li>
              <li><a href='#'><img src="/public/iM/images/networkworld-logo.png" alt="" /></a></li>
              <li><a href='#'><img src="/public/iM/images/technology-review-logo.png" alt="" /></a></li>
              <li><a href='#'><img src="/public/iM/images/networkworld-logo.png" alt="" /></a></li>
              <li><a href='#'><img src="/public/iM/images/technology-review-logo.png" alt="" /></a></li>
            </ul>
          </div>
        </div>
-->
        <div class="cl"></div>
      </div>
    </div>
  </div>
  <!-- body ends -->
  <div class="casestudie-outer">
    <div class="case-body">
      <div class="case-study fl">
        <h2><a href="case-study.html">Case Studies</a></h2>
        <ul>
   

<li> <img src="/public/iM/images/case-study-logo.jpg" alt="" />
            <p>ICT Lanto approached iMarketingB2B with a problem that was all too familiar.
              They had spent years establishing strong relationships and create a brand that establishes trust with any of their customers. However, this was only
              75% of the effort within the B2B market place. The remainder of the 25% was to ensure these established customers clearly knew what was offered for each and every one of their projects. </p>
            <a href="case-detail2.html">Read Case Study</a>
            <div class="cl"></div>
          </li>
        </ul>
      </div>
      <div class="testimonial fr">
        <div class="avatar"><img src="/public/iM/images/testimonial-pic.jpg" alt="" /></div>
        <h2>Testimonials</h2>
        <div class="cl"></div>
        <p><span>Pericom's sales rep approach requires our marketing message to be clear and easy to understand. What's more clear that to provide simple recommendation on exactly what our customers wants?</span></p>
        <div class="user">Nial Van Wagner, <span> Vice President of Sales, Pericom</span></div>
      </div>
      <div class="cl"></div>
    </div>
  </div>
  <!-- footer starts -->
  <div class="footer-outer">
    <footer>
      <div class="btm-logo"><img src="/public/iM/images/bottom-logo.jpg" alt="bottom-logo" /></div>
      <div class="footer-links-container">
        <ul class="btm-links">
          <li class="first"><a href="index">Home </a></li>
          <li><a href="/index/products"> Products </a></li>
          <li><a href="/index/api"> API </a></li>
          <li><a href="/index/algopricing"> Pricing </a></li>
          <li><a href="/index/about"> About Us </a></li>
          <li><a href="/index/jobs"> Jobs</a></li>
        </ul>
        <p class="copyrights">&copy; Copyright 2012 iMarketing B2B.com . All Rights Reserved</p>
        <div class="cl"></div>
      </div>
      <div class="cl"></div>
    </footer>
  </div>
  <!-- footer ends -->
</div>
</body>
</html>
