<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ImarketingB2B</title>
<link rel="stylesheet" href="/public/iM/css/style.css" type="text/css">
<script src="/public/iM/js//jquery.js" type="text/javascript"></script>
<!-- watermark starts -->
<script type="text/javascript" src="/public/iM/js//watermark.js"></script>
<script type="text/javascript">
            var Init = function() {
                watermark("email", "Your Email Address");           
                watermark("password", "Your Password");           
                         }
            if (window.addEventListener)
                window.addEventListener("load", Init, false)
            else if (window.attachEvent)
                window.attachEvent("onload", Init)
            else if (document.getElementById)
                window.onload = Init;
    
</script>
<!-- watermark ends -->
</head>
<body>
<div class="signinBox" style="display:block; margin:0; left:0; top:0; position:relative"> <span class="topbg"></span>
  <div class="midbg">
    <div class="container">
      <h2>Sign In to iMarketing B2B</h2>
      <div class="row">
        <input name="" class="inputtxt" type="text" id="email" />
      </div>
      <div class="row">
        <input name="" class="inputtxt" type="text" id="password" />
      </div>
      <div class="row2">
        <input name="" type="image" src="/public/iM/images/submit-btn-bg.png" value="submit" />
        <span><a href="#">Forgot password?</a></span></div>
    </div>
  </div>
  <span class="bottbg"></span> </div>
</body>
</html>