<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ImarketingB2B</title>
<link rel="stylesheet" href="/public/iM/css/style.css" type="text/css">
<script src="/public/iM/js/html5.js" type="text/javascript"></script>
<script src="/public/iM/js/jquery.js" type="text/javascript"></script>
<!-- watermark starts -->
<script type="text/javascript" src="/public/iM/js/watermark.js"></script>
<script type="text/javascript">
            var Init = function() {
                watermark("email", "Your Email Address");           
                watermark("password", "Your Password");           
                         }
            if (window.addEventListener)
                window.addEventListener("load", Init, false)
            else if (window.attachEvent)
                window.attachEvent("onload", Init)
            else if (document.getElementById)
                window.onload = Init;
    
</script>
<!-- watermark ends -->
</head>
<body>
<div class="layout">
  <!-- header starts -->
  <div class="header-outer">
    <header>
      <div class="logo"><a href="index"><img src="/public/iM/images/logo.jpg" alt="logo" /></a></div>
      <div class="top-right">
        <div class="register">
          <ul>
            <li><a href="#">Signup</a></li>
            <li class="brdr-right"><a href="#">Sign In </a>
              <div class="cl"></div>
              <div class="signinBox"> <span class="topbg"></span>
                <div class="midbg">
                  <div class="container">
                    <h2>Sign In to iMarketing B2B</h2>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="email" />
                    </div>
                    <div class="row">
                      <input name="" class="inputtxt" type="text" id="password" />
                    </div>
                    <div class="row2">
                      <input name="" type="image" src="/public/iM/images/submit-btn-bg.png" value="submit" />
                      <span><a href="#">Forgot password?</a></span></div>
                  </div>
                </div>
                <span class="bottbg"></span> </div>
            </li>
          </ul>
        </div>
        <div class="cl"></div>
        <nav class="nav">
          <ul>
            <li class="first"><a href="index">Home </a></li>
            <li><a href="/index/products" class="cur"> Products </a></li>
            <li><a href="/index/api"> API </a></li>
            <li><a href="/index/algopricing"> Pricing </a></li>
            <li><a href="/index/about"> About Us </a></li>
            <li><a href="/index/jobs"> Jobs</a></li>
          </ul>
        </nav>
      </div>
      <div class="cl"></div>
    </header>
  </div>
  <!-- header ends -->
  <!-- inner page links -->
  <div class="submenu-outer">
    <div class="submenu">
      <h2> Products </h2>
    </div>
  </div>
  <!-- inner page links ends -->
  <!-- body starts -->
  <div class="body-outer">
    <div class="inner-body">
      <div class="products-container">
        <div class="irecommengine"><img src="/public/iM/images/irecommengine-pic.jpg" alt="irecommengine-pic" /><br>
          <a href="recommengine-pricing.html"><img src="/public/iM/images/get-a-price-quote.png" width="206" height="44" alt="get price quote"></a> </div>
        <div class="irecommengine no-padding"><img src="/public/iM/images/algo-intelligent-faq-pic.jpg" alt="algo-intelligent-faq-pic" /> <br>
          <a href="algo-pricing.html"><img src="/public/iM/images/get-a-price-quote.png" width="206" height="44" alt="get price quote"></a> </div>
        <div class="cl"></div>
      </div>
      <div class="content-div">
        <p>Nunc imperdiet nulla sit amet lorem ornare faucibus. Nullam varius tempus dui, ut euismod leo blandit at. Cras velit sapien, euismod bibendum ullamcorper sit amet, posuere et dui. Suspendisse tempor semper libero, at suscipit neque rhoncus et. Fusce sed nibh massa. Aliquam erat volutpat. Integer faucibus vulputate odio ac lacinia. Nulla tempus dictum nisl, quis condimentum lorem mollis in. Aenean fermentum posuere odio et molestie. Vivamus nec nisi lorem. Curabitur sollicitudin, nibh et tincidunt placerat, metus mauris vulputate tellus, non viverra eros velit convallis metus. </p>
      </div>
    </div>
  </div>
  <!-- body ends -->
  <!-- footer starts -->
  <div class="footer-outer">
    <footer>
      <div class="btm-logo"><img src="/public/iM/images/bottom-logo.jpg" alt="bottom-logo" /></div>
      <div class="footer-links-container">
        <ul class="btm-links">
          <li class="first"><a href="index">Home </a></li>
          <li><a href="/index/products"> Products </a></li>
          <li><a href="/index/api"> API </a></li>
          <li><a href="/index/algo-pricing"> Pricing </a></li>
          <li><a href="/index/about"> About Us </a></li>
          <li><a href="/index/jobs"> Jobs</a></li>
        </ul>
        <p class="copyrights">&copy; Copyright 2012 iMarketing B2B.com . All Rights Reserved</p>
        <div class="cl"></div>
      </div>
      <div class="cl"></div>
    </footer>
  </div>
  <!-- footer ends -->
</div>
</body>
</html>
