<form mothod="POST" action="http://www.algorithms.io/api/v1/class/Mapping/method/userFields/authToken/<?php echo $this->authToken; ?>">
File id_seq: <input type="text" name="datasource_id_seq" value="<?php echo $this->id_seq; ?>"/><br/>
field_user_id: <input type="text" name="field_user_id"/><br/>
field_item_id: <input type="text" name="field_item_id"/><br/>
field_preference: <input type="text" name="field_preference"/><br/>

<input type="submit" value="submit"/><br/>

</form>
